properties:
  ml:creation_method_detail:
    type: string
    required: false
  ml:boundary_type:
    type: enum
    required: true
    enum:
      - field
      - parcel
      - hedge
      - other
  ml:verified_from:
    type: date-time
    required: true
  ml:verified_until:
    type: date-time
    required: true
  ml:author:
    type: string
    required: true
  ml:confidence:
    type: float
    required: false
  ml:crop_type:
    type: enum
    required: false
    enum:
      - maize
      - corn
      - potato
      - tomato
      - unknown
  ml:crop_category:
    type: enum
    required: false
    enum:
      - cereal
      - grain
      - legumes
      - unknown
  ml:split_name:
    type: enum
    required: false
    enum:
      - train
      - val
      - test
      - test_public
      - test_private
  ml:split_idx:
    type: uint16
    required: false