properties:
  ml:creation_method:
    type: enum
    required: true
  ml:creation_method_detail:
    type: string
    required: true
  ml:ml:boundary_type:
    type: enum
    required: true
  ml:creation_date:
    type: date-time
    required: false
  ml:verified_from:
    type: date-time
    required: true
  ml:verified_until:
    type: date-time
    required: true
  ml:author:
    type: string
    required: true
  ml:quality:
    type: enum
    required: true
  ml:confidence:
    type: float
    required: false
  ml:machine_generated:
    type: boolean
    required: false
  ml:country_code:
    type: string
    required: true
  ml:admin0:
    type: string
    required: true
  ml:admin1:
    type: string
    required: true
  ml:admin2:
    type: string
    required: true
  ml:crop_type:
    type: enum
    required: false
  ml:crop_category:
    type: enum
    required: true
